import structlog

from app.agents.state import (
    FormattedComment,
    ReviewState,
    SecurityFinding,
)

logger = structlog.get_logger()

_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "ERROR": "🟠",
    "WARNING": "⚠️",
    "INFO": "ℹ️",
    "HIGH": "🔴",
    "MEDIUM": "🟡",
    "LOW": "🟢",
}

_RISK_EMOJI = {
    "LOW": "🟢",
    "MEDIUM": "🟡",
    "HIGH": "🟠",
    "CRITICAL": "🔴",
}


def _format_issue_body(issue) -> str:
    emoji = _SEVERITY_EMOJI.get(issue.severity, "ℹ️")
    lines = [
        f"{emoji} **{issue.severity.capitalize()}** | `{issue.category.lower()}`",
        "",
        issue.message,
    ]
    if issue.suggestion:
        lines += ["", "```suggestion", issue.suggestion, "```"]
    return "\n".join(lines)


def _format_security_body(finding: SecurityFinding) -> str:
    emoji = _SEVERITY_EMOJI.get(finding.severity, "⚠️")
    cwe = f" ({finding.cwe_id})" if finding.cwe_id else ""
    return (
        f"{emoji} **Security** | `{finding.severity.lower()}`{cwe}\n\n"
        f"{finding.description}"
    )


def comment_formatter(state: ReviewState) -> dict:
    """Node 8: Convert AI analysis results into GitHub-compatible review objects.

    Produces:
    - formatted_comments: list[FormattedComment] — inline comment objects
    - review_body: str — the full markdown body for the top-level PR review comment

    The formatted_comments list maps directly to the GitHub PR Review API's
    `comments` array (path + line + side + body).
    The review_body is the main review comment rendered at the top of the PR.
    """
    file_reviews = state.get("file_reviews", [])
    security_findings = state.get("security_findings", [])
    overall_risk = state.get("overall_risk", "LOW")
    complexity_scores = state.get("complexity_scores") or {}
    risk = complexity_scores.get("overall")
    filtered_files = state.get("filtered_files", [])
    skipped_files = state.get("skipped_files", [])
    summary = state.get("summary", "")
    walkthrough = state.get("walkthrough", "")

    inline_comments: list[FormattedComment] = []

    # ── Inline comments from file reviews ────────────────────────────────
    for review in file_reviews:
        for issue in review.issues:
            body = _format_issue_body(issue)
            inline_comments.append(FormattedComment(
                path=review.filename,
                line=max(1, issue.line),
                start_line=None,
                body=body,
            ))

    # ── Inline comments from security findings ───────────────────────────
    for finding in security_findings:
        body = _format_security_body(finding)
        inline_comments.append(FormattedComment(
            path=finding.file,
            line=max(1, finding.line),
            start_line=None,
            body=body,
        ))

    # ── Build top-level review body ───────────────────────────────────────
    total_issues = sum(len(r.issues) for r in file_reviews)
    warning_count = sum(1 for r in file_reviews for i in r.issues if i.severity == "WARNING")
    suggestion_count = sum(1 for r in file_reviews for i in r.issues if i.severity == "INFO")

    risk_emoji = _RISK_EMOJI.get(overall_risk, "🟢")
    complexity_line = (
        f"- Complexity: {risk.score}/10 — {risk.reasoning}"
        if risk else ""
    )

    # Skipped files section
    skipped_section = ""
    if skipped_files:
        skipped_lines = "\n".join(
            f"- `{s['filename']}` — {s['reason']}" for s in skipped_files
        )
        skipped_section = f"\n<details><summary>⏭️ Skipped Files ({len(skipped_files)})</summary>\n\n{skipped_lines}\n\n</details>\n"

    review_body = f"""\
## 🔍 CodeSight Review

### Summary
{summary}

### Walkthrough
{walkthrough}

### Risk Assessment
**Overall Risk: {risk_emoji} {overall_risk.capitalize()}**
- Security: {len(security_findings)} finding(s)
{complexity_line}
- Files changed: {len(filtered_files)} reviewed, {len(skipped_files)} skipped

---
<details><summary>📊 Stats</summary>

- Files reviewed: {len(filtered_files)} / {len(filtered_files) + len(skipped_files)}
- Inline comments: {len(inline_comments)} ({warning_count} warnings, {suggestion_count} suggestions)
- Security findings: {len(security_findings)}

</details>
{skipped_section}
---
*Generated by [CodeSight](https://github.com) — AI Code Review*\
"""

    logger.info(
        "comment_formatter_done",
        inline_comments=len(inline_comments),
        review_body_len=len(review_body),
    )

    return {
        "formatted_comments": inline_comments,
        "review_body": review_body,
    }
